/*
 * $Revision$ $Date$ $Author$
 * 
 * Copyright (C) 2007  National Library of the Netherlands, Nationaal Archief of the Netherlands
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * For more information about this project, visit
 * http://dioscuri.sourceforge.net/
 * or contact us via email:
 * jrvanderhoeven at users.sourceforge.net
 * blohman at users.sourceforge.net
 * 
 * Developed by:
 * Nationaal Archief               <www.nationaalarchief.nl>
 * Koninklijke Bibliotheek         <www.kb.nl>
 * Tessella Support Services plc   <www.tessella.com>
 *
 * Project Title: DIOSCURI
 *
 */

package nl.kbna.dioscuri.module.keyboard;


/**
 * Class ScanCodeSets
 * Defines three basic sets of scancodes: XT, AT and PS/2. By default scancode set AT is used.
 * Notes:
 * - Not all scancodes are filled in.
 * - Difference between XT and AT is that they use different codes
 * - Difference between XT/AT and PS/2 is that the latter doesn't use make/break codes but rather one code.
 * 
 */
public class ScanCodeSets
{
    // 8042 translation table
	// Translates scancodes to XT scancode set (for compatibility)
	// Used when command byte bit 6 (scancodeTranslate) is set
    protected char[] translate8042 = new char[]
                {
                0xff,0x43,0x41,0x3f,0x3d,0x3b,0x3c,0x58,0x64,0x44,0x42,0x40,0x3e,0x0f,0x29,0x59,
                0x65,0x38,0x2a,0x70,0x1d,0x10,0x02,0x5a,0x66,0x71,0x2c,0x1f,0x1e,0x11,0x03,0x5b,
                0x67,0x2e,0x2d,0x20,0x12,0x05,0x04,0x5c,0x68,0x39,0x2f,0x21,0x14,0x13,0x06,0x5d,
                0x69,0x31,0x30,0x23,0x22,0x15,0x07,0x5e,0x6a,0x72,0x32,0x24,0x16,0x08,0x09,0x5f,
                0x6b,0x33,0x25,0x17,0x18,0x0b,0x0a,0x60,0x6c,0x34,0x35,0x26,0x27,0x19,0x0c,0x61,
                0x6d,0x73,0x28,0x74,0x1a,0x0d,0x62,0x6e,0x3a,0x36,0x1c,0x1b,0x75,0x2b,0x63,0x76,
                0x55,0x56,0x77,0x78,0x79,0x7a,0x0e,0x7b,0x7c,0x4f,0x7d,0x4b,0x47,0x7e,0x7f,0x6f,
                0x52,0x53,0x50,0x4c,0x4d,0x48,0x01,0x45,0x57,0x4e,0x51,0x4a,0x37,0x49,0x46,0x54,
                0x80,0x81,0x82,0x41,0x54,0x85,0x86,0x87,0x88,0x89,0x8a,0x8b,0x8c,0x8d,0x8e,0x8f,
                0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9a,0x9b,0x9c,0x9d,0x9e,0x9f,
                0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8,0xa9,0xaa,0xab,0xac,0xad,0xae,0xaf,
                0xb0,0xb1,0xb2,0xb3,0xb4,0xb5,0xb6,0xb7,0xb8,0xb9,0xba,0xbb,0xbc,0xbd,0xbe,0xbf,
                0xc0,0xc1,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7,0xc8,0xc9,0xca,0xcb,0xcc,0xcd,0xce,0xcf,
                0xd0,0xd1,0xd2,0xd3,0xd4,0xd5,0xd6,0xd7,0xd8,0xd9,0xda,0xdb,0xdc,0xdd,0xde,0xdf,
                0xe0,0xe1,0xe2,0xe3,0xe4,0xe5,0xe6,0xe7,0xe8,0xe9,0xea,0xeb,0xec,0xed,0xee,0xef,
                0xf0,0xf1,0xf2,0xf3,0xf4,0xf5,0xf6,0xf7,0xf8,0xf9,0xfa,0xfb,0xfc,0xfd,0xfe,0xff
                };
        
    // VK <-> scancode conversion map
    // Contains scancodes for 3 scancode sets (XT, AT, PS/2)
    String[][][] scancodes = new String[][][]
        {
        // Set 1: XT 
        //          * if make code is 'c', break code will be 'c+0x80'
        //          * if make code is 'E0 c', break code will be 'E0 c+0x80'
        //          
                {   // idx  VK key name    IBM idx #   Make  Break
                    /* 0:   VK_UNDEFINED            */ {"",  ""},
                    /* 1:   nothing (filler)        */ {"",  ""},
                    /* 2:   nothing (filler)        */ {"",  ""},
                    /* 3:   VK_CANCEL               */ {"",  ""},
                    /* 4:   nothing (filler)        */ {"",  ""},
                    /* 5:   nothing (filler)        */ {"",  ""},
                    /* 6:   nothing (filler)        */ {"",  ""},
                    /* 7:   nothing (filler)        */ {"",  ""},
                    /* 8:   VK_BACK_SPACE  (IBM 15) */ {"0E",  "8E"},
                    /* 9:   VK_TAB         (IBM 16) */ {"0F",  "8F"},
                    /* 10:  VK_ENTER       (IBM 43) */ {"1C",  "9C"},
                    /* 11:  Enter-numpad  (IBM 108) */ {"E0 1C",  "E0 9C"},
                    /* 12:  VK_CLEAR                */ {"",  ""},
                    /* 13:  Shift-left     (IBM 44) */ {"2A",  "AA"},
                    /* 14:  Control-left   (IBM 58) */ {"1D",  "9D"},
                    /* 15:  Alt-left       (IBM 60) */ {"38",  "B8"},
                    /* 16:  VK_SHIFT-right (IBM 57) */ {"36",  "B6"},
                    /* 17:  VK_CONTROL-right(IBM 64) */{"E0 1D",  "E0 9D"},
                    /* 18:  VK_ALT-right   (IBM 62) */ {"E0 38",  "E0 B8"},
                    /* 19:  VK_PAUSE      (IBM 126) */ {"E1 1D 45 E1 9D C5",  ""},
                    /* 20:  VK_CAPS_LOCK   (IBM 30) */ {"3A",  "BA"},
                    /* 21:  VK_KANA                 */ {"",  ""},
                    /* 22:  nothing (filler)        */ {"",  ""},
                    /* 23:  nothing (filler)        */ {"",  ""},
                    /* 24:  VK_FINAL                */ {"",  ""},
                    /* 25:  VK_KANJI                */ {"",  ""},
                    /* 26:  nothing (filler)        */ {"",  ""},
                    /* 27:  VK_ESCAPE     (IBM 110) */ {"01",  "81"},
                    /* 28:  VK_CONVERT              */ {"",  ""},
                    /* 29:  VK_NONCONVERT           */ {"",  ""},
                    /* 30:  VK_ACCEPT               */ {"",  ""},
                    /* 31:  VK_MODECHANGE           */ {"",  ""},
                    /* 32:  VK_SPACE       (IBM 61) */ {"39",  "B9"},
                    /* 33:  VK_PAGE_UP     (IBM 85) */ {"E0 49",  "E0 C9"},
                    /* 34:  VK_PAGE_DOWN   (IBM 86) */ {"E0 51",  "E0 D1"},
                    /* 35:  VK_END         (IBM 81) */ {"E0 4F",  "E0 CF"},
                    /* 36:  VK_HOME        (IBM 80) */ {"E0 47",  "E0 C7"},
                    /* 37:  VK_LEFT        (IBM 79) */ {"E0 4B",  "E0 CB"},
                    /* 38:  VK_UP          (IBM 83) */ {"E0 48",  "E0 C8"},
                    /* 39:  VK_RIGHT       (IBM 89) */ {"E0 4D",  "E0 CD"},
                    /* 40:  VK_DOWN        (IBM 84) */ {"E0 50",  "E0 D0"},
                    /* 41:  nothing (filler)        */ {"",  ""},
                    /* 42:  nothing (filler)        */ {"",  ""},
                    /* 43:  nothing (filler)        */ {"",  ""},
                    /* 44:  VK_COMMA       (IBM 53) */ {"33",  "B3"},
                    /* 45:  VK_MINUS       (IBM 12) */ {"0C",  "8C"},
                    /* 46:  VK_PERIOD      (IBM 54) */ {"34",  "B4"},
                    /* 47:  VK_SLASH       (IBM 55) */ {"35",  "B5"},
                    /* 48:  VK_0           (IBM 11) */ {"0B",  "8B"},
                    /* 49:  VK_1           (IBM 2)  */ {"02",  "82"},
                    /* 50:  VK_2           (IBM 3)  */ {"03",  "82"},
                    /* 51:  VK_3           (IBM 4)  */ {"04",  "84"},
                    /* 52:  VK_4           (IBM 5)  */ {"05",  "85"},
                    /* 53:  VK_5           (IBM 6)  */ {"06",  "86"},
                    /* 54:  VK_6           (IBM 7)  */ {"07",  "87"},
                    /* 55:  VK_7           (IBM 8)  */ {"08",  "88"},
                    /* 56:  VK_8           (IBM 9)  */ {"09",  "89"},
                    /* 57:  VK_9           (IBM 10) */ {"0A",  "8A"},
                    /* 58:  nothing (filler)        */ {"",  ""},
                    /* 59:  VK_SEMICOLON   (IBM 40) */ {"27",  "A7"},
                    /* 60:  nothing (filler)        */ {"",  ""},
                    /* 61:  VK_EQUALS      (IBM 13) */ {"0D",  "8D"},
                    /* 62:  nothing (filler)        */ {"",  ""},
                    /* 63:  nothing (filler)        */ {"",  ""},
                    /* 64:  nothing (filler)        */ {"",  ""},
                    /* 65:  VK_A           (IBM 31) */ {"1E",  "9E"},
                    /* 66:  VK_B           (IBM 50) */ {"30",  "B0"},
                    /* 67:  VK_C           (IBM 48) */ {"2E",  "AE"},
                    /* 68:  VK_D           (IBM 33) */ {"20",  "A0"},
                    /* 69:  VK_E           (IBM 19) */ {"12",  "92"},
                    /* 70:  VK_F           (IBM 34) */ {"21",  "A1"},
                    /* 71:  VK_G           (IBM 35) */ {"22",  "A2"},
                    /* 72:  VK_H           (IBM 36) */ {"23",  "A3"},
                    /* 73:  VK_I           (IBM 24) */ {"17",  "97"},
                    /* 74:  VK_J           (IBM 37) */ {"24",  "A4"},
                    /* 75:  VK_K           (IBM 38) */ {"25",  "A5"},
                    /* 76:  VK_L           (IBM 39) */ {"26",  "A6"},
                    /* 77:  VK_M           (IBM 52) */ {"32",  "B2"},
                    /* 78:  VK_N           (IBM 51) */ {"31",  "B1"},
                    /* 79:  VK_O           (IBM 25) */ {"18",  "98"},
                    /* 80:  VK_P           (IBM 26) */ {"19",  "99"},
                    /* 81:  VK_Q           (IBM 17) */ {"10",  "90"},
                    /* 82:  VK_R           (IBM 20) */ {"13",  "93"},
                    /* 83:  VK_S           (IBM 32) */ {"1F",  "9F"},
                    /* 84:  VK_T           (IBM 21) */ {"14",  "94"},
                    /* 85:  VK_U           (IBM 23) */ {"16",  "96"},
                    /* 86:  VK_V           (IBM 49) */ {"2F",  "AF"},
                    /* 87:  VK_W           (IBM 18) */ {"11",  "91"},
                    /* 88:  VK_X           (IBM 47) */ {"2D",  "AD"},
                    /* 89:  VK_Y           (IBM 22) */ {"15",  "95"},
                    /* 90:  VK_Z           (IBM 46) */ {"2C",  "AC"},
                    /* 91:  VK_OPEN_BRACKET(IBM 27) */ {"1A",  "9A"},
                    /* 92:  VK_BACK_SLASH  (IBM 29, 42, 45) */ {"2B",  "AB"},
                    /* 93:  VK_CLOSE_BRACKET(IBM 28)*/ {"1B",  "9B"},
                    /* 94:  nothing (filler)        */ {"",  ""},
                    /* 95:  nothing (filler)        */ {"",  ""},
                    /* 96:  VK_NUMPAD0     (IBM 99) */ {"52",  "D2"},
                    /* 97:  VK_NUMPAD1     (IBM 93) */ {"4F",  "CF"},
                    /* 98:  VK_NUMPAD2     (IBM 98) */ {"50",  "D0"},
                    /* 99:  VK_NUMPAD3    (IBM 103) */ {"51",  "D1"},
                    /* 100: VK_NUMPAD4     (IBM 92) */ {"4B",  "CB"},
                    /* 101: VK_NUMPAD5     (IBM 97) */ {"4C",  "CC"},
                    /* 102: VK_NUMPAD6    (IBM 102) */ {"4D",  "CD"},
                    /* 103: VK_NUMPAD7     (IBM 91) */ {"47",  "C7"},
                    /* 104: VK_NUMPAD8     (IBM 96) */ {"48",  "C8"},
                    /* 105: VK_NUMPAD9    (IBM 101) */ {"49",  "C9"},
                    /* 106: VK_MULTIPLY   (IBM 100) */ {"37",  "D3"},
                    /* 107: VK_ADD        (IBM 106) */ {"4E",  "CE"},
                    /* 108: VK_SEPARATOR            */ {"",  ""},
                    /* 109: VK_SUBTRACT   (IBM 105) */ {"4A",  "CA"},
                    /* 110: VK_DECIMAL    (IBM 104) */ {"53",  "D3"},
                    /* 111: VK_DIVIDE      (IBM 95) */ {"E0 35",  "E0 B5"},
                    /* 112: VK_F1         (IBM 112) */ {"3B",  "BB"},
                    /* 113: VK_F2         (IBM 113) */ {"3C",  "BC"},
                    /* 114: VK_F3         (IBM 114) */ {"3D",  "BD"},
                    /* 115: VK_F4         (IBM 115) */ {"3E",  "BE"},
                    /* 116: VK_F5         (IBM 116) */ {"3F",  "BF"},
                    /* 117: VK_F6         (IBM 117) */ {"40",  "C0"},
                    /* 118: VK_F7         (IBM 118) */ {"41",  "C1"},
                    /* 119: VK_F8         (IBM 119) */ {"42",  "C2"},
                    /* 120: VK_F9         (IBM 120) */ {"43",  "C3"},
                    /* 121: VK_F10        (IBM 121) */ {"44",  "C4"},
                    /* 122: VK_F11        (IBM 122) */ {"57",  "D7"},
                    /* 123: VK_F12        (IBM 123) */ {"58",  "D8"},
                    /* 124: nothing (filler)        */ {"",  ""},
                    /* 125: nothing (filler)        */ {"",  ""},
                    /* 126: nothing (filler)        */ {"",  ""},
                    /* 127: VK_DELETE      (IBM 76) */ {"E0 53",  "E0 D3"},
                    /* 128: VK_DEAD_GRAVE           */ {"29",  "A9"},	// Set similar as 192
                    /* 129: VK_DEAD_ACUTE           */ {"28",  "A8"},	// Set similar as 222
                    /* 130: VK_DEAD_CIRCUMFLEX      */ {"",  ""},
                    /* 131: VK_DEAD_TILDE           */ {"",  ""},
                    /* 132: VK_DEAD_MACRON          */ {"",  ""},
                    /* 133: VK_DEAD_BREVE           */ {"",  ""},
                    /* 134: VK_DEAD_ABOVEDOT        */ {"",  ""},
                    /* 135: VK_DEAD_DIAERESIS       */ {"",  ""},
                    /* 136: VK_DEAD_ABOVERING       */ {"",  ""},
                    /* 137: VK_DEAD_DOUBLEACUTE     */ {"",  ""},
                    /* 138: VK_DEAD_CARON           */ {"",  ""},
                    /* 139: VK_DEAD_CEDILLA         */ {"",  ""},
                    /* 140: VK_DEAD_OGONEK          */ {"",  ""},
                    /* 141: VK_DEAD_IOTA            */ {"",  ""},
                    /* 142: VK_DEAD_VOICED_SOUND    */ {"",  ""},
                    /* 143: VK_DEAD_SEMIVOICED_SOUND*/ {"",  ""},
                    /* 144: VK_NUM_LOCK    (IBM 90) */ {"45",  "C5"},
                    /* 145: VK_SCROLL_LOCK (IBM 125)*/ {"46",  "C6"},
                    /* 146: nothing (filler)        */ {"",  ""},
                    /* 147: nothing (filler)        */ {"",  ""},
                    /* 148: nothing (filler)        */ {"",  ""},
                    /* 149: nothing (filler)        */ {"",  ""},
                    /* 150: VK_AMPERSAND            */ {"",  ""},
                    /* 151: VK_ASTERISK             */ {"",  ""},
                    /* 152: VK_QUOTEDBL             */ {"",  ""},
                    /* 153: VK_LESS                 */ {"",  ""},
                    /* 154: VK_PRINTSCREEN          */ {"",  ""},
                    /* 155: VK_INSERT      (IBM 75) */ {"E0 52",  "E0 D2"},
                    /* 156: VK_HELP                 */ {"",  ""},
                    /* 157: VK_META                 */ {"",  ""},
                    /* 158: nothing (filler)        */ {"",  ""},
                    /* 159: nothing (filler)        */ {"",  ""},
                    /* 160: VK_GREATER              */ {"",  ""},
                    /* 161: VK_BRACELEFT            */ {"",  ""},
                    /* 162: VK_BRACERIGHT           */ {"",  ""},
                    /* 163: nothing (filler)        */ {"",  ""},
                    /* 164: nothing (filler)        */ {"",  ""},
                    /* 165: nothing (filler)        */ {"",  ""},
                    /* 166: nothing (filler)        */ {"",  ""},
                    /* 167: nothing (filler)        */ {"",  ""},
                    /* 168: nothing (filler)        */ {"",  ""},
                    /* 169: nothing (filler)        */ {"",  ""},
                    /* 170: nothing (filler)        */ {"",  ""},
                    /* 171: nothing (filler)        */ {"",  ""},
                    /* 172: nothing (filler)        */ {"",  ""},
                    /* 173: nothing (filler)        */ {"",  ""},
                    /* 174: nothing (filler)        */ {"",  ""},
                    /* 175: nothing (filler)        */ {"",  ""},
                    /* 176: nothing (filler)        */ {"",  ""},
                    /* 177: nothing (filler)        */ {"",  ""},
                    /* 178: nothing (filler)        */ {"",  ""},
                    /* 179: nothing (filler)        */ {"",  ""},
                    /* 180: nothing (filler)        */ {"",  ""},
                    /* 181: nothing (filler)        */ {"",  ""},
                    /* 182: nothing (filler)        */ {"",  ""},
                    /* 183: nothing (filler)        */ {"",  ""},
                    /* 184: nothing (filler)        */ {"",  ""},
                    /* 185: nothing (filler)        */ {"",  ""},
                    /* 186: nothing (filler)        */ {"",  ""},
                    /* 187: nothing (filler)        */ {"",  ""},
                    /* 188: nothing (filler)        */ {"",  ""},
                    /* 189: nothing (filler)        */ {"",  ""},
                    /* 190: nothing (filler)        */ {"",  ""},
                    /* 191: nothing (filler)        */ {"",  ""},
                    /* 192: VK_BACK_QUOTE   (IBM 1) */ {"29",  "A9"},
                    /* 193: nothing (filler)        */ {"",  ""},
                    /* 194: nothing (filler)        */ {"",  ""},
                    /* 195: nothing (filler)        */ {"",  ""},
                    /* 196: nothing (filler)        */ {"",  ""},
                    /* 197: nothing (filler)        */ {"",  ""},
                    /* 198: nothing (filler)        */ {"",  ""},
                    /* 199: nothing (filler)        */ {"",  ""},
                    /* 200: nothing (filler)        */ {"",  ""},
                    /* 201: nothing (filler)        */ {"",  ""},
                    /* 202: nothing (filler)        */ {"",  ""},
                    /* 203: nothing (filler)        */ {"",  ""},
                    /* 204: nothing (filler)        */ {"",  ""},
                    /* 205: nothing (filler)        */ {"",  ""},
                    /* 206: nothing (filler)        */ {"",  ""},
                    /* 207: nothing (filler)        */ {"",  ""},
                    /* 208: nothing (filler)        */ {"",  ""},
                    /* 209: nothing (filler)        */ {"",  ""},
                    /* 210: nothing (filler)        */ {"",  ""},
                    /* 211: nothing (filler)        */ {"",  ""},
                    /* 212: nothing (filler)        */ {"",  ""},
                    /* 213: nothing (filler)        */ {"",  ""},
                    /* 214: nothing (filler)        */ {"",  ""},
                    /* 215: nothing (filler)        */ {"",  ""},
                    /* 216: nothing (filler)        */ {"",  ""},
                    /* 217: nothing (filler)        */ {"",  ""},
                    /* 218: nothing (filler)        */ {"",  ""},
                    /* 219: nothing (filler)        */ {"",  ""},
                    /* 220: nothing (filler)        */ {"",  ""},
                    /* 221: nothing (filler)        */ {"",  ""},
                    /* 222: VK_QUOTE       (IBM 41) */ {"28",  "A8"},
                    /* 223: nothing (filler)        */ {"",  ""},
                    /* 224: VK_KP_UP                */ {"",  ""},
                    /* 225: VK_KP_DOWN              */ {"",  ""},
                    /* 226: VK_KP_LEFT              */ {"",  ""},
                    /* 227: VK_KP_RIGHT             */ {"",  ""},
                    /* 228: nothing (filler)        */ {"",  ""},
                    /* 229: nothing (filler)        */ {"",  ""},
                    /* 230: nothing (filler)        */ {"",  ""},
                    /* 231: nothing (filler)        */ {"",  ""},
                    /* 232: nothing (filler)        */ {"",  ""},
                    /* 233: nothing (filler)        */ {"",  ""},
                    /* 234: nothing (filler)        */ {"",  ""},
                    /* 235: nothing (filler)        */ {"",  ""},
                    /* 236: nothing (filler)        */ {"",  ""},
                    /* 237: nothing (filler)        */ {"",  ""},
                    /* 238: nothing (filler)        */ {"",  ""},
                    /* 239: nothing (filler)        */ {"",  ""},
                    /* 240: VK_ALPHANUMERIC         */ {"",  ""},
                    /* 241: VK_KATAKANA             */ {"",  ""},
                    /* 242: VK_HIRAGANA             */ {"",  ""},
                    /* 243: VK_FULL_WIDTH           */ {"",  ""},
                    /* 244: VK_HALF_WIDTH           */ {"",  ""},
                    /* 245: VK_ROMAN_CHARACTERS     */ {"",  ""},
                    /* 246: nothing (filler)        */ {"",  ""},
                    /* 247: nothing (filler)        */ {"",  ""},
                    /* 248: nothing (filler)        */ {"",  ""},
                    /* 249: nothing (filler)        */ {"",  ""},
                    /* 250: nothing (filler)        */ {"",  ""},
                    /* 251: nothing (filler)        */ {"",  ""},
                    /* 252: nothing (filler)        */ {"",  ""},
                    /* 253: nothing (filler)        */ {"",  ""},
                    /* 254: nothing (filler)        */ {"",  ""},
                    /* 255: nothing (filler)        */ {"",  ""},
                    /* 256: VK_ALL_CANDIDATES       */ {"",  ""},
                    /* 257: VK_PREVIOUS_CANDIDATE   */ {"",  ""},
                    /* 258: VK_CODE_INPUT           */ {"",  ""},
                    /* 259: VK_JAPANESE_KATAKANA    */ {"",  ""},
                    /* 260: VK_JAPANESE_HIRAGANA    */ {"",  ""},
                    /* 261: VK_JAPANESE_ROMAN       */ {"",  ""},
                    /* 262: VK_KANA_LOCK            */ {"",  ""},
                    /* 263: VK_INPUT_METHOD_ON_OFF  */ {"",  ""},

                    /* 512: VK_AT                   */ {"",  ""},
                    /* 513: VK_COLON                */ {"",  ""},
                    /* 514: VK_CIRCUMFLEX           */ {"",  ""},
                    /* 515: VK_DOLLAR               */ {"",  ""},
                    /* 516: VK_EURO_SIGN            */ {"",  ""},
                    /* 517: VK_EXCLAMATION_MARK     */ {"",  ""},
                    /* 518: VK_INVERTED_EXCLAMATION_MARK*/ {"",  ""},
                    /* 519: VK_LEFT_PARENTHESIS     */ {"",  ""},
                    /* 520: VK_NUMBER_SIGN          */ {"",  ""},
                    /* 521: VK_PLUS                 */ {"",  ""},
                    /* 522: VK_RIGHT_PARENTHESIS    */ {"",  ""},
                    /* 523: VK_UNDERSCORE           */ {"",  ""},
                    /* 524: VK_WINDOWS (IBM L-Win, R-Win)*/ {"E0 5B",  ""},
                    /* 525: VK_CONTEXT_MENU (IBM Apps)   */ {"E0 5D",  ""},
                    /* 61440: VK_F13                */ {"",  ""},
                    /* 61441: VK_F14                */ {"",  ""},
                    /* 61442: VK_F15                */ {"",  ""},
                    /* 61443: VK_F16                */ {"",  ""},
                    /* 61444: VK_F17                */ {"",  ""},
                    /* 61445: VK_F18                */ {"",  ""},
                    /* 61446: VK_F19                */ {"",  ""},
                    /* 61447: VK_F20                */ {"",  ""},
                    /* 61448: VK_F21                */ {"",  ""},
                    /* 61449: VK_F22                */ {"",  ""},
                    /* 61450: VK_F23                */ {"",  ""},
                    /* 61451: VK_F24                */ {"",  ""},
                    /* 65312: VK_COMPOSE            */ {"",  ""},
                    /* 65368: VK_BEGIN              */ {"",  ""},
                    /* 65406: VK_ALT_GRAPH          */ {"",  ""},
                    /* 65480: VK_STOP               */ {"",  ""},
                    /* 65481: VK_AGAIN              */ {"",  ""},
                    /* 65482: VK_PROPS              */ {"",  ""},
                    /* 65483: VK_UNDO               */ {"",  ""},
                    /* 65485: VK_COPY               */ {"",  ""},
                    /* 65487: VK_PASTE              */ {"",  ""},
                    /* 65488: VK_FIND               */ {"",  ""},
                    /* 65489: VK_CUT                */ {"",  ""}
                },
        // Set 2: AT 
        //          * if make code is 'c', break code will be 'F0 c'
        //          * if make code is 'E0 c', break code will be 'E0 F0 c'
        //
                {   // idx  VK key name    IBM idx #   Make  Break
                    /* 0:   VK_UNDEFINED            */ {"",  ""},
                    /* 1:   nothing (filler)        */ {"",  ""},
                    /* 2:   nothing (filler)        */ {"",  ""},
                    /* 3:   VK_CANCEL               */ {"",  ""},
                    /* 4:   nothing (filler)        */ {"",  ""},
                    /* 5:   nothing (filler)        */ {"",  ""},
                    /* 6:   nothing (filler)        */ {"",  ""},
                    /* 7:   nothing (filler)        */ {"",  ""},
                    /* 8:   VK_BACK_SPACE  (IBM 15) */ {"66",  "F0 66"},
                    /* 9:   VK_TAB         (IBM 16) */ {"0D",  "F0 0D"},
                    /* 10:  VK_ENTER       (IBM 43) */ {"5A",  "F0 5A"},
                    /* 11:  Enter-numpad  (IBM 108) */ {"E0 5A",  "E0 F0 5A"},
                    /* 12:  VK_CLEAR                */ {"",  ""},
                    /* 13:  Shift-left     (IBM 44) */ {"12",  "F0 12"},
                    /* 14:  Control-left   (IBM 58) */ {"14",  "F0 14"},
                    /* 15:  Alt-left       (IBM 60) */ {"11",  "F0 11"},
                    /* 16:  VK_SHIFT-right (IBM 57) */ {"59",  "F0 59"},
                    /* 17:  VK_CONTROL-right(IBM 64) */{"E0 14",  "E0 F0 14"},
                    /* 18:  VK_ALT-right   (IBM 62) */ {"E0 11",  "E0 F0 11"},
                    /* 19:  VK_PAUSE      (IBM 126) */ {"E1 1D 45 E1 9D C5",  ""},
                    /* 20:  VK_CAPS_LOCK   (IBM 30) */ {"58",  "F0 58"},
                    /* 21:  VK_KANA                 */ {"",  ""},
                    /* 22:  nothing (filler)        */ {"",  ""},
                    /* 23:  nothing (filler)        */ {"",  ""},
                    /* 24:  VK_FINAL                */ {"",  ""},
                    /* 25:  VK_KANJI                */ {"",  ""},
                    /* 26:  nothing (filler)        */ {"",  ""},
                    /* 27:  VK_ESCAPE     (IBM 110) */ {"76",  "F0 56"},
                    /* 28:  VK_CONVERT              */ {"",  ""},
                    /* 29:  VK_NONCONVERT           */ {"",  ""},
                    /* 30:  VK_ACCEPT               */ {"",  ""},
                    /* 31:  VK_MODECHANGE           */ {"",  ""},
                    /* 32:  VK_SPACE       (IBM 61) */ {"29",  "F0 29"},
                    /* 33:  VK_PAGE_UP     (IBM 85) */ {"E0 7D",  "E0 F0 7D"},
                    /* 34:  VK_PAGE_DOWN   (IBM 86) */ {"E0 7A",  "E0 F0 7A"},
                    /* 35:  VK_END         (IBM 81) */ {"E0 69",  "E0 F0 69"},
                    /* 36:  VK_HOME        (IBM 80) */ {"E0 6C",  "E0 F0 6C"},
                    /* 37:  VK_LEFT        (IBM 79) */ {"E0 6B",  "E0 F0 6B"},
                    /* 38:  VK_UP          (IBM 83) */ {"E0 75",  "E0 F0 75"},
                    /* 39:  VK_RIGHT       (IBM 89) */ {"E0 74",  "E0 F0 74"},
                    /* 40:  VK_DOWN        (IBM 84) */ {"E0 72",  "E0 F0 72"},
                    /* 41:  nothing (filler)        */ {"",  ""},
                    /* 42:  nothing (filler)        */ {"",  ""},
                    /* 43:  nothing (filler)        */ {"",  ""},
                    /* 44:  VK_COMMA       (IBM 53) */ {"41",  "F0 41"},
                    /* 45:  VK_MINUS       (IBM 12) */ {"4E",  "F0 4E"},
                    /* 46:  VK_PERIOD      (IBM 54) */ {"49",  "F0 49"},
                    /* 47:  VK_SLASH       (IBM 55) */ {"4A",  "F0 4A"},
                    /* 48:  VK_0           (IBM 11) */ {"45",  "F0 45"},
                    /* 49:  VK_1           (IBM 2)  */ {"16",  "F0 16"},
                    /* 50:  VK_2           (IBM 3)  */ {"1E",  "F0 1E"},
                    /* 51:  VK_3           (IBM 4)  */ {"26",  "F0 26"},
                    /* 52:  VK_4           (IBM 5)  */ {"25",  "F0 25"},
                    /* 53:  VK_5           (IBM 6)  */ {"2E",  "F0 2E"},
                    /* 54:  VK_6           (IBM 7)  */ {"36",  "F0 36"},
                    /* 55:  VK_7           (IBM 8)  */ {"3D",  "F0 3D"},
                    /* 56:  VK_8           (IBM 9)  */ {"3E",  "F0 3E"},
                    /* 57:  VK_9           (IBM 10) */ {"46",  "F0 46"},
                    /* 58:  nothing (filler)        */ {"",  ""},
                    /* 59:  VK_SEMICOLON   (IBM 40) */ {"4C",  "F0 4C"},
                    /* 60:  nothing (filler)        */ {"",  ""},
                    /* 61:  VK_EQUALS      (IBM 13) */ {"55",  "F0 55"},
                    /* 62:  nothing (filler)        */ {"",  ""},
                    /* 63:  nothing (filler)        */ {"",  ""},
                    /* 64:  nothing (filler)        */ {"",  ""},
                    /* 65:  VK_A           (IBM 31) */ {"1C",  "F0 1C"},
                    /* 66:  VK_B           (IBM 50) */ {"32",  "F0 32"},
                    /* 67:  VK_C           (IBM 48) */ {"21",  "F0 21"},
                    /* 68:  VK_D           (IBM 33) */ {"23",  "F0 23"},
                    /* 69:  VK_E           (IBM 19) */ {"24",  "F0 24"},
                    /* 70:  VK_F           (IBM 34) */ {"2B",  "F0 2B"},
                    /* 71:  VK_G           (IBM 35) */ {"34",  "F0 34"},
                    /* 72:  VK_H           (IBM 36) */ {"33",  "F0 33"},
                    /* 73:  VK_I           (IBM 24) */ {"43",  "F0 43"},
                    /* 74:  VK_J           (IBM 37) */ {"3B",  "F0 3B"},
                    /* 75:  VK_K           (IBM 38) */ {"42",  "F0 42"},
                    /* 76:  VK_L           (IBM 39) */ {"4B",  "F0 4B"},
                    /* 77:  VK_M           (IBM 52) */ {"3A",  "F0 3A"},
                    /* 78:  VK_N           (IBM 51) */ {"31",  "F0 31"},
                    /* 79:  VK_O           (IBM 25) */ {"44",  "F0 44"},
                    /* 80:  VK_P           (IBM 26) */ {"4D",  "F0 4D"},
                    /* 81:  VK_Q           (IBM 17) */ {"15",  "F0 15"},
                    /* 82:  VK_R           (IBM 20) */ {"2D",  "F0 2D"},
                    /* 83:  VK_S           (IBM 32) */ {"1B",  "F0 1B"},
                    /* 84:  VK_T           (IBM 21) */ {"2C",  "F0 2C"},
                    /* 85:  VK_U           (IBM 23) */ {"3C",  "F0 3C"},
                    /* 86:  VK_V           (IBM 49) */ {"2A",  "F0 2A"},
                    /* 87:  VK_W           (IBM 18) */ {"1D",  "F0 1D"},
                    /* 88:  VK_X           (IBM 47) */ {"22",  "F0 22"},
                    /* 89:  VK_Y           (IBM 22) */ {"35",  "F0 35"},
                    /* 90:  VK_Z           (IBM 46) */ {"1A",  "F0 1A"},
                    /* 91:  VK_OPEN_BRACKET(IBM 27) */ {"54",  "F0 54"},
                    /* 92:  VK_BACK_SLASH  (IBM 29, 42, 45) */ {"5D",  "F0 5D"},
                    /* 93:  VK_CLOSE_BRACKET(IBM 28)*/ {"5B",  "F0 5B"},
                    /* 94:  nothing (filler)        */ {"",  ""},
                    /* 95:  nothing (filler)        */ {"",  ""},
                    /* 96:  VK_NUMPAD0     (IBM 99) */ {"70",  "F0 70"},
                    /* 97:  VK_NUMPAD1     (IBM 93) */ {"69",  "F0 69"},
                    /* 98:  VK_NUMPAD2     (IBM 98) */ {"72",  "F0 72"},
                    /* 99:  VK_NUMPAD3    (IBM 103) */ {"7A",  "F0 7A"},
                    /* 100: VK_NUMPAD4     (IBM 92) */ {"6B",  "F0 6B"},
                    /* 101: VK_NUMPAD5     (IBM 97) */ {"73",  "F0 73"},
                    /* 102: VK_NUMPAD6    (IBM 102) */ {"74",  "F0 74"},
                    /* 103: VK_NUMPAD7     (IBM 91) */ {"6C",  "F0 6C"},
                    /* 104: VK_NUMPAD8     (IBM 96) */ {"75",  "F0 75"},
                    /* 105: VK_NUMPAD9    (IBM 101) */ {"7D",  "F0 7D"},
                    /* 106: VK_MULTIPLY   (IBM 100) */ {"7C",  "F0 7C"},
                    /* 107: VK_ADD        (IBM 106) */ {"79",  "F0 79"},
                    /* 108: VK_SEPARATOR            */ {"",  ""},
                    /* 109: VK_SUBTRACT   (IBM 105) */ {"7B",  "F0 7B"},
                    /* 110: VK_DECIMAL    (IBM 104) */ {"71",  "F0 71"},
                    /* 111: VK_DIVIDE      (IBM 95) */ {"E0 4A",  "E0 F0 4A"},
                    /* 112: VK_F1         (IBM 112) */ {"05",  "F0 05"},
                    /* 113: VK_F2         (IBM 113) */ {"06",  "F0 06"},
                    /* 114: VK_F3         (IBM 114) */ {"04",  "F0 04"},
                    /* 115: VK_F4         (IBM 115) */ {"0C",  "F0 0C"},
                    /* 116: VK_F5         (IBM 116) */ {"03",  "F0 03"},
                    /* 117: VK_F6         (IBM 117) */ {"0B",  "F0 0B"},
                    /* 118: VK_F7         (IBM 118) */ {"83",  "F0 83"},
                    /* 119: VK_F8         (IBM 119) */ {"0A",  "F0 0A"},
                    /* 120: VK_F9         (IBM 120) */ {"01",  "F0 01"},
                    /* 121: VK_F10        (IBM 121) */ {"09",  "F0 09"},
                    /* 122: VK_F11        (IBM 122) */ {"78",  "F0 78"},
                    /* 123: VK_F12        (IBM 123) */ {"07",  "F0 07"},
                    /* 124: nothing (filler)        */ {"",  ""},
                    /* 125: nothing (filler)        */ {"",  ""},
                    /* 126: nothing (filler)        */ {"",  ""},
                    /* 127: VK_DELETE      (IBM 76) */ {"E0 71",  "E0 F0 71"},
                    /* 128: VK_DEAD_GRAVE           */ {"0E",  "F0 0E"},	// Set similar as 192
                    /* 129: VK_DEAD_ACUTE           */ {"52",  "F0 52"},	// Set similar as 222
                    /* 130: VK_DEAD_CIRCUMFLEX      */ {"",  ""},
                    /* 131: VK_DEAD_TILDE           */ {"",  ""},
                    /* 132: VK_DEAD_MACRON          */ {"",  ""},
                    /* 133: VK_DEAD_BREVE           */ {"",  ""},
                    /* 134: VK_DEAD_ABOVEDOT        */ {"",  ""},
                    /* 135: VK_DEAD_DIAERESIS       */ {"",  ""},
                    /* 136: VK_DEAD_ABOVERING       */ {"",  ""},
                    /* 137: VK_DEAD_DOUBLEACUTE     */ {"",  ""},
                    /* 138: VK_DEAD_CARON           */ {"",  ""},
                    /* 139: VK_DEAD_CEDILLA         */ {"",  ""},
                    /* 140: VK_DEAD_OGONEK          */ {"",  ""},
                    /* 141: VK_DEAD_IOTA            */ {"",  ""},
                    /* 142: VK_DEAD_VOICED_SOUND    */ {"",  ""},
                    /* 143: VK_DEAD_SEMIVOICED_SOUND*/ {"",  ""},
                    /* 144: VK_NUM_LOCK    (IBM 90) */ {"77",  "F0 77"},
                    /* 145: VK_SCROLL_LOCK (IBM 125)*/ {"7E",  "F0 7E"},
                    /* 146: nothing (filler)        */ {"",  ""},
                    /* 147: nothing (filler)        */ {"",  ""},
                    /* 148: nothing (filler)        */ {"",  ""},
                    /* 149: nothing (filler)        */ {"",  ""},
                    /* 150: VK_AMPERSAND            */ {"",  ""},
                    /* 151: VK_ASTERISK             */ {"",  ""},
                    /* 152: VK_QUOTEDBL             */ {"",  ""},
                    /* 153: VK_LESS                 */ {"",  ""},
                    /* 154: VK_PRINTSCREEN          */ {"",  ""},
                    /* 155: VK_INSERT      (IBM 75) */ {"E0 70",  "E0 F0 70"},
                    /* 156: VK_HELP                 */ {"",  ""},
                    /* 157: VK_META                 */ {"",  ""},
                    /* 158: nothing (filler)        */ {"",  ""},
                    /* 159: nothing (filler)        */ {"",  ""},
                    /* 160: VK_GREATER              */ {"",  ""},
                    /* 161: VK_BRACELEFT            */ {"",  ""},
                    /* 162: VK_BRACERIGHT           */ {"",  ""},
                    /* 163: nothing (filler)        */ {"",  ""},
                    /* 164: nothing (filler)        */ {"",  ""},
                    /* 165: nothing (filler)        */ {"",  ""},
                    /* 166: nothing (filler)        */ {"",  ""},
                    /* 167: nothing (filler)        */ {"",  ""},
                    /* 168: nothing (filler)        */ {"",  ""},
                    /* 169: nothing (filler)        */ {"",  ""},
                    /* 170: nothing (filler)        */ {"",  ""},
                    /* 171: nothing (filler)        */ {"",  ""},
                    /* 172: nothing (filler)        */ {"",  ""},
                    /* 173: nothing (filler)        */ {"",  ""},
                    /* 174: nothing (filler)        */ {"",  ""},
                    /* 175: nothing (filler)        */ {"",  ""},
                    /* 176: nothing (filler)        */ {"",  ""},
                    /* 177: nothing (filler)        */ {"",  ""},
                    /* 178: nothing (filler)        */ {"",  ""},
                    /* 179: nothing (filler)        */ {"",  ""},
                    /* 180: nothing (filler)        */ {"",  ""},
                    /* 181: nothing (filler)        */ {"",  ""},
                    /* 182: nothing (filler)        */ {"",  ""},
                    /* 183: nothing (filler)        */ {"",  ""},
                    /* 184: nothing (filler)        */ {"",  ""},
                    /* 185: nothing (filler)        */ {"",  ""},
                    /* 186: nothing (filler)        */ {"",  ""},
                    /* 187: nothing (filler)        */ {"",  ""},
                    /* 188: nothing (filler)        */ {"",  ""},
                    /* 189: nothing (filler)        */ {"",  ""},
                    /* 190: nothing (filler)        */ {"",  ""},
                    /* 191: nothing (filler)        */ {"",  ""},
                    /* 192: VK_BACK_QUOTE   (IBM 1) */ {"0E",  "F0 0E"},
                    /* 193: nothing (filler)        */ {"",  ""},
                    /* 194: nothing (filler)        */ {"",  ""},
                    /* 195: nothing (filler)        */ {"",  ""},
                    /* 196: nothing (filler)        */ {"",  ""},
                    /* 197: nothing (filler)        */ {"",  ""},
                    /* 198: nothing (filler)        */ {"",  ""},
                    /* 199: nothing (filler)        */ {"",  ""},
                    /* 200: nothing (filler)        */ {"",  ""},
                    /* 201: nothing (filler)        */ {"",  ""},
                    /* 202: nothing (filler)        */ {"",  ""},
                    /* 203: nothing (filler)        */ {"",  ""},
                    /* 204: nothing (filler)        */ {"",  ""},
                    /* 205: nothing (filler)        */ {"",  ""},
                    /* 206: nothing (filler)        */ {"",  ""},
                    /* 207: nothing (filler)        */ {"",  ""},
                    /* 208: nothing (filler)        */ {"",  ""},
                    /* 209: nothing (filler)        */ {"",  ""},
                    /* 210: nothing (filler)        */ {"",  ""},
                    /* 211: nothing (filler)        */ {"",  ""},
                    /* 212: nothing (filler)        */ {"",  ""},
                    /* 213: nothing (filler)        */ {"",  ""},
                    /* 214: nothing (filler)        */ {"",  ""},
                    /* 215: nothing (filler)        */ {"",  ""},
                    /* 216: nothing (filler)        */ {"",  ""},
                    /* 217: nothing (filler)        */ {"",  ""},
                    /* 218: nothing (filler)        */ {"",  ""},
                    /* 219: nothing (filler)        */ {"",  ""},
                    /* 220: nothing (filler)        */ {"",  ""},
                    /* 221: nothing (filler)        */ {"",  ""},
                    /* 222: VK_QUOTE       (IBM 41) */ {"52",  "F0 52"},
                    /* 223: nothing (filler)        */ {"",  ""},
                    /* 224: VK_KP_UP                */ {"",  ""},
                    /* 225: VK_KP_DOWN              */ {"",  ""},
                    /* 226: VK_KP_LEFT              */ {"",  ""},
                    /* 227: VK_KP_RIGHT             */ {"",  ""},
                    /* 228: nothing (filler)        */ {"",  ""},
                    /* 229: nothing (filler)        */ {"",  ""},
                    /* 230: nothing (filler)        */ {"",  ""},
                    /* 231: nothing (filler)        */ {"",  ""},
                    /* 232: nothing (filler)        */ {"",  ""},
                    /* 233: nothing (filler)        */ {"",  ""},
                    /* 234: nothing (filler)        */ {"",  ""},
                    /* 235: nothing (filler)        */ {"",  ""},
                    /* 236: nothing (filler)        */ {"",  ""},
                    /* 237: nothing (filler)        */ {"",  ""},
                    /* 238: nothing (filler)        */ {"",  ""},
                    /* 239: nothing (filler)        */ {"",  ""},
                    /* 240: VK_ALPHANUMERIC         */ {"",  ""},
                    /* 241: VK_KATAKANA             */ {"",  ""},
                    /* 242: VK_HIRAGANA             */ {"",  ""},
                    /* 243: VK_FULL_WIDTH           */ {"",  ""},
                    /* 244: VK_HALF_WIDTH           */ {"",  ""},
                    /* 245: VK_ROMAN_CHARACTERS     */ {"",  ""},
                    /* 246: nothing (filler)        */ {"",  ""},
                    /* 247: nothing (filler)        */ {"",  ""},
                    /* 248: nothing (filler)        */ {"",  ""},
                    /* 249: nothing (filler)        */ {"",  ""},
                    /* 250: nothing (filler)        */ {"",  ""},
                    /* 251: nothing (filler)        */ {"",  ""},
                    /* 252: nothing (filler)        */ {"",  ""},
                    /* 253: nothing (filler)        */ {"",  ""},
                    /* 254: nothing (filler)        */ {"",  ""},
                    /* 255: nothing (filler)        */ {"",  ""},
                    /* 256: VK_ALL_CANDIDATES       */ {"",  ""},
                    /* 257: VK_PREVIOUS_CANDIDATE   */ {"",  ""},
                    /* 258: VK_CODE_INPUT           */ {"",  ""},
                    /* 259: VK_JAPANESE_KATAKANA    */ {"",  ""},
                    /* 260: VK_JAPANESE_HIRAGANA    */ {"",  ""},
                    /* 261: VK_JAPANESE_ROMAN       */ {"",  ""},
                    /* 262: VK_KANA_LOCK            */ {"",  ""},
                    /* 263: VK_INPUT_METHOD_ON_OFF  */ {"",  ""},

                    /* 512: VK_AT                   */ {"",  ""},
                    /* 513: VK_COLON                */ {"",  ""},
                    /* 514: VK_CIRCUMFLEX           */ {"",  ""},
                    /* 515: VK_DOLLAR               */ {"",  ""},
                    /* 516: VK_EURO_SIGN            */ {"",  ""},
                    /* 517: VK_EXCLAMATION_MARK     */ {"",  ""},
                    /* 518: VK_INVERTED_EXCLAMATION_MARK*/ {"",  ""},
                    /* 519: VK_LEFT_PARENTHESIS     */ {"",  ""},
                    /* 520: VK_NUMBER_SIGN          */ {"",  ""},
                    /* 521: VK_PLUS                 */ {"",  ""},
                    /* 522: VK_RIGHT_PARENTHESIS    */ {"",  ""},
                    /* 523: VK_UNDERSCORE           */ {"",  ""},
                    /* 524: VK_WINDOWS (IBM L-Win, R-Win)*/ {"E0 1F",  "E0 F0 F1"},
                    /* 525: VK_CONTEXT_MENU (IBM Apps)   */ {"E0 2F",  "E0 F0 2F"},
                    /* 61440: VK_F13                */ {"",  ""},
                    /* 61441: VK_F14                */ {"",  ""},
                    /* 61442: VK_F15                */ {"",  ""},
                    /* 61443: VK_F16                */ {"",  ""},
                    /* 61444: VK_F17                */ {"",  ""},
                    /* 61445: VK_F18                */ {"",  ""},
                    /* 61446: VK_F19                */ {"",  ""},
                    /* 61447: VK_F20                */ {"",  ""},
                    /* 61448: VK_F21                */ {"",  ""},
                    /* 61449: VK_F22                */ {"",  ""},
                    /* 61450: VK_F23                */ {"",  ""},
                    /* 61451: VK_F24                */ {"",  ""},
                    /* 65312: VK_COMPOSE            */ {"",  ""},
                    /* 65368: VK_BEGIN              */ {"",  ""},
                    /* 65406: VK_ALT_GRAPH          */ {"",  ""},
                    /* 65480: VK_STOP               */ {"",  ""},
                    /* 65481: VK_AGAIN              */ {"",  ""},
                    /* 65482: VK_PROPS              */ {"",  ""},
                    /* 65483: VK_UNDO               */ {"",  ""},
                    /* 65485: VK_COPY               */ {"",  ""},
                    /* 65487: VK_PASTE              */ {"",  ""},
                    /* 65488: VK_FIND               */ {"",  ""},
                    /* 65489: VK_CUT                */ {"",  ""}
                },        
        // Set 3: PS/2
        //          * if make code is 'c', break code will be 'F0 c'
        //          * if make code is 'E0 c', break code will be 'E0 F0 c'
        //
                {   // idx  VK key name    IBM idx #   Make  Break
                    /* 0:   VK_UNDEFINED            */ {"",  ""},
                    /* 1:   nothing (filler)        */ {"",  ""},
                    /* 2:   nothing (filler)        */ {"",  ""},
                    /* 3:   VK_CANCEL               */ {"",  ""},
                    /* 4:   nothing (filler)        */ {"",  ""},
                    /* 5:   nothing (filler)        */ {"",  ""},
                    /* 6:   nothing (filler)        */ {"",  ""},
                    /* 7:   nothing (filler)        */ {"",  ""},
                    /* 8:   VK_BACK_SPACE  (IBM 15) */ {"66",  "F0 66"},
                    /* 9:   VK_TAB         (IBM 16) */ {"0D",  "F0 0D"},
                    /* 10:  VK_ENTER       (IBM 43) */ {"5A",  "F0 5A"},
                    /* 11:  Enter-numpad  (IBM 108) */ {"79",  "F0 79"},
                    /* 12:  VK_CLEAR                */ {"",  ""},
                    /* 13:  Shift-left     (IBM 44) */ {"12",  "F0 12"},
                    /* 14:  Control-left   (IBM 58) */ {"11",  "F0 11"},
                    /* 15:  Alt-left       (IBM 60) */ {"19",  "F0 19"},
                    /* 16:  VK_SHIFT-right (IBM 57) */ {"59",  "F0 59"},
                    /* 17:  VK_CONTROL-right(IBM 64) */{"58",  "F0 58"},
                    /* 18:  VK_ALT-right   (IBM 62) */ {"39",  "F0 39"},
                    /* 19:  VK_PAUSE      (IBM 126) */ {"62",  "F0 62"},
                    /* 20:  VK_CAPS_LOCK   (IBM 30) */ {"14",  "F0 14"},
                    /* 21:  VK_KANA                 */ {"",  ""},
                    /* 22:  nothing (filler)        */ {"",  ""},
                    /* 23:  nothing (filler)        */ {"",  ""},
                    /* 24:  VK_FINAL                */ {"",  ""},
                    /* 25:  VK_KANJI                */ {"",  ""},
                    /* 26:  nothing (filler)        */ {"",  ""},
                    /* 27:  VK_ESCAPE     (IBM 110) */ {"08",  "F0 08"},
                    /* 28:  VK_CONVERT              */ {"",  ""},
                    /* 29:  VK_NONCONVERT           */ {"",  ""},
                    /* 30:  VK_ACCEPT               */ {"",  ""},
                    /* 31:  VK_MODECHANGE           */ {"",  ""},
                    /* 32:  VK_SPACE       (IBM 61) */ {"29",  "F0 29"},
                    /* 33:  VK_PAGE_UP     (IBM 85) */ {"6F",  "F0 6F"},
                    /* 34:  VK_PAGE_DOWN   (IBM 86) */ {"6D",  "F0 6D"},
                    /* 35:  VK_END         (IBM 81) */ {"65",  "F0 65"},
                    /* 36:  VK_HOME        (IBM 80) */ {"6E",  "F0 6E"},
                    /* 37:  VK_LEFT        (IBM 79) */ {"61",  "F0 61"},
                    /* 38:  VK_UP          (IBM 83) */ {"63",  "F0 63"},
                    /* 39:  VK_RIGHT       (IBM 89) */ {"6A",  "F0 6A"},
                    /* 40:  VK_DOWN        (IBM 84) */ {"60",  "F0 60"},
                    /* 41:  nothing (filler)        */ {"",  ""},
                    /* 42:  nothing (filler)        */ {"",  ""},
                    /* 43:  nothing (filler)        */ {"",  ""},
                    /* 44:  VK_COMMA       (IBM 53) */ {"41",  "F0 41"},
                    /* 45:  VK_MINUS       (IBM 12) */ {"4E",  "F0 4E"},
                    /* 46:  VK_PERIOD      (IBM 54) */ {"49",  "F0 49"},
                    /* 47:  VK_SLASH       (IBM 55) */ {"4A",  "F0 4A"},
                    /* 48:  VK_0           (IBM 11) */ {"45",  "F0 45"},
                    /* 49:  VK_1           (IBM 2)  */ {"16",  "F0 16"},
                    /* 50:  VK_2           (IBM 3)  */ {"1E",  "F0 1E"},
                    /* 51:  VK_3           (IBM 4)  */ {"26",  "F0 26"},
                    /* 52:  VK_4           (IBM 5)  */ {"25",  "F0 25"},
                    /* 53:  VK_5           (IBM 6)  */ {"2E",  "F0 2E"},
                    /* 54:  VK_6           (IBM 7)  */ {"36",  "F0 36"},
                    /* 55:  VK_7           (IBM 8)  */ {"3D",  "F0 3D"},
                    /* 56:  VK_8           (IBM 9)  */ {"3E",  "F0 3E"},
                    /* 57:  VK_9           (IBM 10) */ {"46",  "F0 46"},
                    /* 58:  nothing (filler)        */ {"",  ""},
                    /* 59:  VK_SEMICOLON   (IBM 40) */ {"4C",  "F0 4C"},
                    /* 60:  nothing (filler)        */ {"",  ""},
                    /* 61:  VK_EQUALS      (IBM 13) */ {"55",  "F0 55"},
                    /* 62:  nothing (filler)        */ {"",  ""},
                    /* 63:  nothing (filler)        */ {"",  ""},
                    /* 64:  nothing (filler)        */ {"",  ""},
                    /* 65:  VK_A           (IBM 31) */ {"1C",  "F0 1C"},
                    /* 66:  VK_B           (IBM 50) */ {"32",  "F0 32"},
                    /* 67:  VK_C           (IBM 48) */ {"21",  "F0 21"},
                    /* 68:  VK_D           (IBM 33) */ {"23",  "F0 23"},
                    /* 69:  VK_E           (IBM 19) */ {"24",  "F0 24"},
                    /* 70:  VK_F           (IBM 34) */ {"2B",  "F0 2B"},
                    /* 71:  VK_G           (IBM 35) */ {"34",  "F0 34"},
                    /* 72:  VK_H           (IBM 36) */ {"33",  "F0 33"},
                    /* 73:  VK_I           (IBM 24) */ {"43",  "F0 43"},
                    /* 74:  VK_J           (IBM 37) */ {"3B",  "F0 3B"},
                    /* 75:  VK_K           (IBM 38) */ {"42",  "F0 42"},
                    /* 76:  VK_L           (IBM 39) */ {"4B",  "F0 4B"},
                    /* 77:  VK_M           (IBM 52) */ {"3A",  "F0 3A"},
                    /* 78:  VK_N           (IBM 51) */ {"31",  "F0 31"},
                    /* 79:  VK_O           (IBM 25) */ {"44",  "F0 44"},
                    /* 80:  VK_P           (IBM 26) */ {"4D",  "F0 4D"},
                    /* 81:  VK_Q           (IBM 17) */ {"15",  "F0 15"},
                    /* 82:  VK_R           (IBM 20) */ {"2D",  "F0 2D"},
                    /* 83:  VK_S           (IBM 32) */ {"1B",  "F0 1B"},
                    /* 84:  VK_T           (IBM 21) */ {"2C",  "F0 2C"},
                    /* 85:  VK_U           (IBM 23) */ {"3C",  "F0 3C"},
                    /* 86:  VK_V           (IBM 49) */ {"2A",  "F0 2A"},
                    /* 87:  VK_W           (IBM 18) */ {"1D",  "F0 1D"},
                    /* 88:  VK_X           (IBM 47) */ {"22",  "F0 22"},
                    /* 89:  VK_Y           (IBM 22) */ {"35",  "F0 35"},
                    /* 90:  VK_Z           (IBM 46) */ {"1A",  "F0 1A"},
                    /* 91:  VK_OPEN_BRACKET(IBM 27) */ {"54",  "F0 54"},
                    /* 92:  VK_BACK_SLASH  (IBM 29, 42, 45) */ {"53",  "F0 53"},
                    /* 93:  VK_CLOSE_BRACKET(IBM 28)*/ {"5B",  "F0 5B"},
                    /* 94:  nothing (filler)        */ {"",  ""},
                    /* 95:  nothing (filler)        */ {"",  ""},
                    /* 96:  VK_NUMPAD0     (IBM 99) */ {"70",  "F0 70"},
                    /* 97:  VK_NUMPAD1     (IBM 93) */ {"69",  "F0 69"},
                    /* 98:  VK_NUMPAD2     (IBM 98) */ {"72",  "F0 72"},
                    /* 99:  VK_NUMPAD3    (IBM 103) */ {"7A",  "F0 7A"},
                    /* 100: VK_NUMPAD4     (IBM 92) */ {"6B",  "F0 6B"},
                    /* 101: VK_NUMPAD5     (IBM 97) */ {"73",  "F0 73"},
                    /* 102: VK_NUMPAD6    (IBM 102) */ {"74",  "F0 74"},
                    /* 103: VK_NUMPAD7     (IBM 91) */ {"6C",  "F0 6C"},
                    /* 104: VK_NUMPAD8     (IBM 96) */ {"75",  "F0 75"},
                    /* 105: VK_NUMPAD9    (IBM 101) */ {"7D",  "F0 7D"},
                    /* 106: VK_MULTIPLY   (IBM 100) */ {"7E",  "F0 7E"},
                    /* 107: VK_ADD        (IBM 106) */ {"7C",  "F0 7C"},
                    /* 108: VK_SEPARATOR            */ {"",  ""},
                    /* 109: VK_SUBTRACT   (IBM 105) */ {"84",  "F0 84"},
                    /* 110: VK_DECIMAL    (IBM 104) */ {"71",  "F0 71"},
                    /* 111: VK_DIVIDE      (IBM 95) */ {"77",  "F0 77"},
                    /* 112: VK_F1         (IBM 112) */ {"07",  "F0 07"},
                    /* 113: VK_F2         (IBM 113) */ {"0F",  "F0 0F"},
                    /* 114: VK_F3         (IBM 114) */ {"17",  "F0 17"},
                    /* 115: VK_F4         (IBM 115) */ {"1F",  "F0 1F"},
                    /* 116: VK_F5         (IBM 116) */ {"27",  "F0 27"},
                    /* 117: VK_F6         (IBM 117) */ {"2F",  "F0 2F"},
                    /* 118: VK_F7         (IBM 118) */ {"37",  "F0 37"},
                    /* 119: VK_F8         (IBM 119) */ {"3F",  "F0 3F"},
                    /* 120: VK_F9         (IBM 120) */ {"47",  "F0 47"},
                    /* 121: VK_F10        (IBM 121) */ {"4F",  "F0 4F"},
                    /* 122: VK_F11        (IBM 122) */ {"56",  "F0 56"},
                    /* 123: VK_F12        (IBM 123) */ {"5E",  "F0 5E"},
                    /* 124: nothing (filler)        */ {"",  ""},
                    /* 125: nothing (filler)        */ {"",  ""},
                    /* 126: nothing (filler)        */ {"",  ""},
                    /* 127: VK_DELETE      (IBM 76) */ {"64",  "F0 64"},
                    /* 128: VK_DEAD_GRAVE           */ {"0E",  "F0 0E"},	// Set similar as 192
                    /* 129: VK_DEAD_ACUTE           */ {"52",  "F0 52"},	// Set similar as 222
                    /* 130: VK_DEAD_CIRCUMFLEX      */ {"",  ""},
                    /* 131: VK_DEAD_TILDE           */ {"",  ""},
                    /* 132: VK_DEAD_MACRON          */ {"",  ""},
                    /* 133: VK_DEAD_BREVE           */ {"",  ""},
                    /* 134: VK_DEAD_ABOVEDOT        */ {"",  ""},
                    /* 135: VK_DEAD_DIAERESIS       */ {"",  ""},
                    /* 136: VK_DEAD_ABOVERING       */ {"",  ""},
                    /* 137: VK_DEAD_DOUBLEACUTE     */ {"",  ""},
                    /* 138: VK_DEAD_CARON           */ {"",  ""},
                    /* 139: VK_DEAD_CEDILLA         */ {"",  ""},
                    /* 140: VK_DEAD_OGONEK          */ {"",  ""},
                    /* 141: VK_DEAD_IOTA            */ {"",  ""},
                    /* 142: VK_DEAD_VOICED_SOUND    */ {"",  ""},
                    /* 143: VK_DEAD_SEMIVOICED_SOUND*/ {"",  ""},
                    /* 144: VK_NUM_LOCK    (IBM 90) */ {"76",  "F0 76"},
                    /* 145: VK_SCROLL_LOCK (IBM 125)*/ {"5F",  "F0 5F"},
                    /* 146: nothing (filler)        */ {"",  ""},
                    /* 147: nothing (filler)        */ {"",  ""},
                    /* 148: nothing (filler)        */ {"",  ""},
                    /* 149: nothing (filler)        */ {"",  ""},
                    /* 150: VK_AMPERSAND            */ {"",  ""},
                    /* 151: VK_ASTERISK             */ {"",  ""},
                    /* 152: VK_QUOTEDBL             */ {"",  ""},
                    /* 153: VK_LESS                 */ {"",  ""},
                    /* 154: VK_PRINTSCREEN          */ {"",  ""},
                    /* 155: VK_INSERT      (IBM 75) */ {"67",  "F0 67"},
                    /* 156: VK_HELP                 */ {"",  ""},
                    /* 157: VK_META                 */ {"",  ""},
                    /* 158: nothing (filler)        */ {"",  ""},
                    /* 159: nothing (filler)        */ {"",  ""},
                    /* 160: VK_GREATER              */ {"",  ""},
                    /* 161: VK_BRACELEFT            */ {"",  ""},
                    /* 162: VK_BRACERIGHT           */ {"",  ""},
                    /* 163: nothing (filler)        */ {"",  ""},
                    /* 164: nothing (filler)        */ {"",  ""},
                    /* 165: nothing (filler)        */ {"",  ""},
                    /* 166: nothing (filler)        */ {"",  ""},
                    /* 167: nothing (filler)        */ {"",  ""},
                    /* 168: nothing (filler)        */ {"",  ""},
                    /* 169: nothing (filler)        */ {"",  ""},
                    /* 170: nothing (filler)        */ {"",  ""},
                    /* 171: nothing (filler)        */ {"",  ""},
                    /* 172: nothing (filler)        */ {"",  ""},
                    /* 173: nothing (filler)        */ {"",  ""},
                    /* 174: nothing (filler)        */ {"",  ""},
                    /* 175: nothing (filler)        */ {"",  ""},
                    /* 176: nothing (filler)        */ {"",  ""},
                    /* 177: nothing (filler)        */ {"",  ""},
                    /* 178: nothing (filler)        */ {"",  ""},
                    /* 179: nothing (filler)        */ {"",  ""},
                    /* 180: nothing (filler)        */ {"",  ""},
                    /* 181: nothing (filler)        */ {"",  ""},
                    /* 182: nothing (filler)        */ {"",  ""},
                    /* 183: nothing (filler)        */ {"",  ""},
                    /* 184: nothing (filler)        */ {"",  ""},
                    /* 185: nothing (filler)        */ {"",  ""},
                    /* 186: nothing (filler)        */ {"",  ""},
                    /* 187: nothing (filler)        */ {"",  ""},
                    /* 188: nothing (filler)        */ {"",  ""},
                    /* 189: nothing (filler)        */ {"",  ""},
                    /* 190: nothing (filler)        */ {"",  ""},
                    /* 191: nothing (filler)        */ {"",  ""},
                    /* 192: VK_BACK_QUOTE   (IBM 1) */ {"0E",  "F0 0E"},
                    /* 193: nothing (filler)        */ {"",  ""},
                    /* 194: nothing (filler)        */ {"",  ""},
                    /* 195: nothing (filler)        */ {"",  ""},
                    /* 196: nothing (filler)        */ {"",  ""},
                    /* 197: nothing (filler)        */ {"",  ""},
                    /* 198: nothing (filler)        */ {"",  ""},
                    /* 199: nothing (filler)        */ {"",  ""},
                    /* 200: nothing (filler)        */ {"",  ""},
                    /* 201: nothing (filler)        */ {"",  ""},
                    /* 202: nothing (filler)        */ {"",  ""},
                    /* 203: nothing (filler)        */ {"",  ""},
                    /* 204: nothing (filler)        */ {"",  ""},
                    /* 205: nothing (filler)        */ {"",  ""},
                    /* 206: nothing (filler)        */ {"",  ""},
                    /* 207: nothing (filler)        */ {"",  ""},
                    /* 208: nothing (filler)        */ {"",  ""},
                    /* 209: nothing (filler)        */ {"",  ""},
                    /* 210: nothing (filler)        */ {"",  ""},
                    /* 211: nothing (filler)        */ {"",  ""},
                    /* 212: nothing (filler)        */ {"",  ""},
                    /* 213: nothing (filler)        */ {"",  ""},
                    /* 214: nothing (filler)        */ {"",  ""},
                    /* 215: nothing (filler)        */ {"",  ""},
                    /* 216: nothing (filler)        */ {"",  ""},
                    /* 217: nothing (filler)        */ {"",  ""},
                    /* 218: nothing (filler)        */ {"",  ""},
                    /* 219: nothing (filler)        */ {"",  ""},
                    /* 220: nothing (filler)        */ {"",  ""},
                    /* 221: nothing (filler)        */ {"",  ""},
                    /* 222: VK_QUOTE       (IBM 41) */ {"52",  "F0 52"},
                    /* 223: nothing (filler)        */ {"",  ""},
                    /* 224: VK_KP_UP                */ {"",  ""},
                    /* 225: VK_KP_DOWN              */ {"",  ""},
                    /* 226: VK_KP_LEFT              */ {"",  ""},
                    /* 227: VK_KP_RIGHT             */ {"",  ""},
                    /* 228: nothing (filler)        */ {"",  ""},
                    /* 229: nothing (filler)        */ {"",  ""},
                    /* 230: nothing (filler)        */ {"",  ""},
                    /* 231: nothing (filler)        */ {"",  ""},
                    /* 232: nothing (filler)        */ {"",  ""},
                    /* 233: nothing (filler)        */ {"",  ""},
                    /* 234: nothing (filler)        */ {"",  ""},
                    /* 235: nothing (filler)        */ {"",  ""},
                    /* 236: nothing (filler)        */ {"",  ""},
                    /* 237: nothing (filler)        */ {"",  ""},
                    /* 238: nothing (filler)        */ {"",  ""},
                    /* 239: nothing (filler)        */ {"",  ""},
                    /* 240: VK_ALPHANUMERIC         */ {"",  ""},
                    /* 241: VK_KATAKANA             */ {"",  ""},
                    /* 242: VK_HIRAGANA             */ {"",  ""},
                    /* 243: VK_FULL_WIDTH           */ {"",  ""},
                    /* 244: VK_HALF_WIDTH           */ {"",  ""},
                    /* 245: VK_ROMAN_CHARACTERS     */ {"",  ""},
                    /* 246: nothing (filler)        */ {"",  ""},
                    /* 247: nothing (filler)        */ {"",  ""},
                    /* 248: nothing (filler)        */ {"",  ""},
                    /* 249: nothing (filler)        */ {"",  ""},
                    /* 250: nothing (filler)        */ {"",  ""},
                    /* 251: nothing (filler)        */ {"",  ""},
                    /* 252: nothing (filler)        */ {"",  ""},
                    /* 253: nothing (filler)        */ {"",  ""},
                    /* 254: nothing (filler)        */ {"",  ""},
                    /* 255: nothing (filler)        */ {"",  ""},
                    /* 256: VK_ALL_CANDIDATES       */ {"",  ""},
                    /* 257: VK_PREVIOUS_CANDIDATE   */ {"",  ""},
                    /* 258: VK_CODE_INPUT           */ {"",  ""},
                    /* 259: VK_JAPANESE_KATAKANA    */ {"",  ""},
                    /* 260: VK_JAPANESE_HIRAGANA    */ {"",  ""},
                    /* 261: VK_JAPANESE_ROMAN       */ {"",  ""},
                    /* 262: VK_KANA_LOCK            */ {"",  ""},
                    /* 263: VK_INPUT_METHOD_ON_OFF  */ {"",  ""},

                    /* 512: VK_AT                   */ {"",  ""},
                    /* 513: VK_COLON                */ {"",  ""},
                    /* 514: VK_CIRCUMFLEX           */ {"",  ""},
                    /* 515: VK_DOLLAR               */ {"",  ""},
                    /* 516: VK_EURO_SIGN            */ {"",  ""},
                    /* 517: VK_EXCLAMATION_MARK     */ {"",  ""},
                    /* 518: VK_INVERTED_EXCLAMATION_MARK*/ {"",  ""},
                    /* 519: VK_LEFT_PARENTHESIS     */ {"",  ""},
                    /* 520: VK_NUMBER_SIGN          */ {"",  ""},
                    /* 521: VK_PLUS                 */ {"",  ""},
                    /* 522: VK_RIGHT_PARENTHESIS    */ {"",  ""},
                    /* 523: VK_UNDERSCORE           */ {"",  ""},
                    /* 524: VK_WINDOWS (IBM L-Win, R-Win)*/ {"8B",  "F0 8B"},
                    /* 525: VK_CONTEXT_MENU (IBM Apps)   */ {"8D",  "F0 8D"},
                    /* 61440: VK_F13                */ {"",  ""},
                    /* 61441: VK_F14                */ {"",  ""},
                    /* 61442: VK_F15                */ {"",  ""},
                    /* 61443: VK_F16                */ {"",  ""},
                    /* 61444: VK_F17                */ {"",  ""},
                    /* 61445: VK_F18                */ {"",  ""},
                    /* 61446: VK_F19                */ {"",  ""},
                    /* 61447: VK_F20                */ {"",  ""},
                    /* 61448: VK_F21                */ {"",  ""},
                    /* 61449: VK_F22                */ {"",  ""},
                    /* 61450: VK_F23                */ {"",  ""},
                    /* 61451: VK_F24                */ {"",  ""},
                    /* 65312: VK_COMPOSE            */ {"",  ""},
                    /* 65368: VK_BEGIN              */ {"",  ""},
                    /* 65406: VK_ALT_GRAPH          */ {"",  ""},
                    /* 65480: VK_STOP               */ {"",  ""},
                    /* 65481: VK_AGAIN              */ {"",  ""},
                    /* 65482: VK_PROPS              */ {"",  ""},
                    /* 65483: VK_UNDO               */ {"",  ""},
                    /* 65485: VK_COPY               */ {"",  ""},
                    /* 65487: VK_PASTE              */ {"",  ""},
                    /* 65488: VK_FIND               */ {"",  ""},
                    /* 65489: VK_CUT                */ {"",  ""}
                },
        };
    
    /**
     * Returns true iff <code>x</code>, <code>y</code> and <code>z</code> are 
     * within the bounds of the three dimensional class variable 
     * <code>String[][][]</code> {@link #scancodes}, else false.
     * @param x the value of the first 'dimension'
     * @param y the value of the second 'dimension'
     * @param z the value of the third 'dimension'
     * @return true iff <code>x</code>, <code>y</code> and <code>z</code> are 
     * within the bounds of the three dimensional class variable 
     * <code>String[][][]</code> {@link #scancodes}, else false.
     */
    protected boolean keyIsPresent(int x, int y, int z) {
        return (x >= 0 && x < scancodes.length) &&
                // 'y >= 3' because 'keyEvent.getKeyCode()-3' is used in KeyBoard
                // 'scancodes[0].length-1' because 'keyEvent.getKeyCode()+1'  is used in KeyBoard
                (y >= 3 && y < scancodes[0].length-1) &&
                (z >= 0 && z < scancodes[0][0].length);
    }
}
